name = "cousins"
main = "src/worker.js"
compatibility_date = "2026-08-21"

[assets]
directory = "./public"
binding = "ASSETS"

kv_namespaces = [
  { binding = "COUSINS_KV", id = "REPLACE_WITH_KV_NAMESPACE_ID" }
]

routes = [
  { pattern = "philipjrepko.com/cousins*", zone_name = "philipjrepko.com" }
]
