name = "cousins"
main = "src/worker.js"
compatibility_date = "2026-08-21"

kv_namespaces = [
  { binding = "COUSINS_KV", id = "cac321cb20254e7a866a140cdce563f2" }
]

workers_dev = true

routes = [
  { pattern = "philipjrepko.com/cousins*", zone_name = "philipjrepko.com" }
]

[assets]
directory = "./public"
binding = "ASSETS"
